[
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 22,
        slots: 0,
        name: "King Beetle Head",
        skills: { "Evade Window": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 22,
        slots: 0,
        name: "Butterfly Head",
        skills: { "Evade Window": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 22,
        slots: 0,
        name: "King Beetle Chest",
        skills: { "Quick Sheath": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 22,
        slots: 0,
        name: "Butterfly Chest",
        skills: { "Quick Sheath": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 22,
        slots: 0,
        name: "King Beetle Arms",
        skills: { "Leap of Faith": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 22,
        slots: 0,
        name: "Butterfly Arms",
        skills: { "Leap of Faith": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 22,
        slots: 0,
        name: "King Beetle Waist",
        skills: { "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 22,
        slots: 0,
        name: "Butterfly Waist",
        skills: { "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 22,
        slots: 0,
        name: "King Beetle Legs",
        skills: { "Forager\u2019s Luck": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 22,
        slots: 0,
        name: "Butterfly Legs",
        skills: { "Forager\u2019s Luck": 1 },
        type: 3
    },
]