[
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Resistance Charm I",
        skills: { "Poison Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Resistance Charm II",
        skills: { "Poison Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Attack Boost Charm I",
        skills: { "Attack Boost": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Attack Boost Charm II",
        skills: { "Attack Boost": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Defense Boost Charm I",
        skills: { "Defense Boost": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Defense Boost Charm II",
        skills: { "Defense Boost": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Resistance Charm I",
        skills: { "Paralysis Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Resistance Charm II",
        skills: { "Paralysis Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Resistance Charm I",
        skills: { "Sleep Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Resistance Charm II",
        skills: { "Sleep Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stun Resistance Charm I",
        skills: { "Stun Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stun Resistance Charm II",
        skills: { "Stun Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Windproof Charm I",
        skills: { Windproof: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Windproof Charm II",
        skills: { Windproof: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Health Boost Charm I",
        skills: { "Health Boost": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Health Boost Charm II",
        skills: { "Health Boost": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Recovery Up Charm I",
        skills: { "Recovery Up": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Recovery Up Charm II",
        skills: { "Recovery Up": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fire Resistance Charm I",
        skills: { "Fire Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fire Resistance Charm II",
        skills: { "Fire Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Water Resistance Charm I",
        skills: { "Water Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Water Resistance Charm II",
        skills: { "Water Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Thunder Resistance Charm I",
        skills: { "Thunder Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Thunder Resistance Charm II",
        skills: { "Thunder Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fire Attack Charm I",
        skills: { "Fire Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fire Attack Charm II",
        skills: { "Fire Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Water Attack Charm I",
        skills: { "Water Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Water Attack Charm II",
        skills: { "Water Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Thunder Attack Charm I",
        skills: { "Thunder Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Thunder Attack Charm II",
        skills: { "Thunder Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Attack Charm I",
        skills: { "Poison Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Attack Charm II",
        skills: { "Poison Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Attack Charm I",
        skills: { "Paralysis Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Attack Charm II",
        skills: { "Paralysis Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Attack Charm I",
        skills: { "Sleep Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Attack Charm II",
        skills: { "Sleep Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Slugger Charm I",
        skills: { Slugger: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Slugger Charm II",
        skills: { Slugger: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stamina Thief Charm I",
        skills: { "Stamina Thief": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stamina Thief Charm II",
        skills: { "Stamina Thief": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Artillery Charm I",
        skills: { Artillery: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Artillery Charm II",
        skills: { Artillery: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Hunger Resistance Charm I",
        skills: { "Hunger Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Hunger Resistance Charm II",
        skills: { "Hunger Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Guard Charm I",
        skills: { Guard: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Guard Charm II",
        skills: { Guard: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Wide-Range Charm I",
        skills: { "Wide-Range": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Wide-Range Charm II",
        skills: { "Wide-Range": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Item Prolonger Charm I",
        skills: { "Item Prolonger": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Item Prolonger Charm II",
        skills: { "Item Prolonger": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Speed Eating Charm I",
        skills: { "Speed Eating": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Speed Eating Charm II",
        skills: { "Speed Eating": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Divine Blessing Charm I",
        skills: { "Divine Blessing": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Divine Blessing Charm II",
        skills: { "Divine Blessing": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Palico Rally Charm I",
        skills: { "Palico Rally": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Palico Rally Charm II",
        skills: { "Palico Rally": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Botanist Charm I",
        skills: { Botanist: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Botanist Charm II",
        skills: { Botanist: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Geologist Charm I",
        skills: { Geologist: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Geologist Charm II",
        skills: { Geologist: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Slinger Capacity Charm I",
        skills: { "Slinger Capacity": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Slinger Capacity Charm II",
        skills: { "Slinger Capacity": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stealth Charm I",
        skills: { Stealth: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stealth Charm II",
        skills: { Stealth: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Survival Expert Charm I",
        skills: { "Survival Expert": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Survival Expert Charm II",
        skills: { "Survival Expert": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Aquatic/Polar Mobility Charm I",
        skills: { "Aquatic/Polar Mobility": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Aquatic/Polar Mobility Charm II",
        skills: { "Aquatic/Polar Mobility": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Entomologist Charm I",
        skills: { Entomologist: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Entomologist Charm II",
        skills: { Entomologist: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Intimidator Charm I",
        skills: { Intimidator: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Intimidator Charm II",
        skills: { Intimidator: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bleeding Resistance Charm I",
        skills: { "Bleeding Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bleeding Resistance Charm II",
        skills: { "Bleeding Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Recovery Speed Charm I",
        skills: { "Recovery Speed": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Recovery Speed Charm II",
        skills: { "Recovery Speed": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Ice Resistance Charm I",
        skills: { "Ice Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Ice Resistance Charm II",
        skills: { "Ice Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blight Resistance Charm I",
        skills: { "Blight Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blight Resistance Charm II",
        skills: { "Blight Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Ice Attack Charm I",
        skills: { "Ice Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Ice Attack Charm II",
        skills: { "Ice Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Critical Eye Charm I",
        skills: { "Critical Eye": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Critical Eye Charm II",
        skills: { "Critical Eye": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Evade Window Charm I",
        skills: { "Evade Window": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Evade Window Charm II",
        skills: { "Evade Window": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Quick Sheath Charm I",
        skills: { "Quick Sheath": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Quick Sheath Charm II",
        skills: { "Quick Sheath": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Speed Sharpening Charm I",
        skills: { "Speed Sharpening": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Speed Sharpening Charm II",
        skills: { "Speed Sharpening": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Resistance Charm I",
        skills: { "Blast Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Resistance Charm II",
        skills: { "Blast Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Dragon Resistance Charm I",
        skills: { "Dragon Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Dragon Resistance Charm II",
        skills: { "Dragon Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Dragon Attack Charm I",
        skills: { "Dragon Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Dragon Attack Charm II",
        skills: { "Dragon Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Attack Charm I",
        skills: { "Blast Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Attack Charm II",
        skills: { "Blast Attack": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Critical Draw Charm I",
        skills: { "Critical Draw": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Special Ammo Boost Charm I",
        skills: { "Special Ammo Boost": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Marathon Runner Charm I",
        skills: { "Marathon Runner": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Constitution Charm I",
        skills: { Constitution: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Constitution Charm II",
        skills: { Constitution: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stamina Surge Charm I",
        skills: { "Stamina Surge": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Evade Extender Charm I",
        skills: { "Evade Extender": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bombardier Charm I",
        skills: { Bombardier: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bombardier Charm II",
        skills: { Bombardier: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Mushroomancer Charm I",
        skills: { Mushroomancer: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Free Elem/Ammo Up Charm I",
        skills: { "Free Elem/Ammo Up": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Handicraft Charm I",
        skills: { Handicraft: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Handicraft Charm II",
        skills: { Handicraft: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Iron Skin Charm I",
        skills: { "Iron Skin": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Iron Skin Charm II",
        skills: { "Iron Skin": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Earplugs Charm I",
        skills: { Earplugs: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Earplugs Charm II",
        skills: { Earplugs: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Tremor Resistance Charm I",
        skills: { "Tremor Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Weakness Exploit Charm I",
        skills: { "Weakness Exploit": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Focus Charm I",
        skills: { Focus: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Partbreaker Charm I",
        skills: { Partbreaker: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Resentment Charm I",
        skills: { Resentment: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Heroics Charm I",
        skills: { Heroics: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Tool Specialist Charm I",
        skills: { "Tool Specialist": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Tool Specialist Charm II",
        skills: { "Tool Specialist": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Latent Power Charm I",
        skills: { "Latent Power": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Agitator Charm I",
        skills: { Agitator: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Peak Performance Charm I",
        skills: { "Peak Performance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Maximum Might Charm I",
        skills: { "Maximum Might": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Flinch Free Charm I",
        skills: { "Flinch Free": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Effluvia Resistance Charm I",
        skills: { "Effluvia Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Effluvia Resistance Charm II",
        skills: { "Effluvia Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Power Prolonger Charm I",
        skills: { "Power Prolonger": 1 },
        type: 3
    },
]