[
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 22,
        slots: 0,
        name: "King Beetle Vertex",
        skills: { "Stun Resistance": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 22,
        slots: 0,
        name: "Queen Beetle Vertex",
        skills: { "Stun Resistance": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 22,
        slots: 0,
        name: "King Beetle Torax",
        skills: { "Health Boost": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 22,
        slots: 0,
        name: "Queen Beetle Torax",
        skills: { "Health Boost": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 22,
        slots: 0,
        name: "King Beetle Brachia",
        skills: { "Critical Eye": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 22,
        slots: 0,
        name: "Queen Beetle Brachia",
        skills: { "Critical Eye": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1,-1, 2, 0, 2],
        part: 3,
        mindef: 22,
        slots: 0,
        name: "King Beetle Elytra",
        skills: { "Defense Boost": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 22,
        slots: 0,
        name: "Queen Beetle Elytra",
        skills: { "Defense Boost": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 22,
        slots: 0,
        name: "King Beetle Crura",
        skills: { "Marathon Runner": 1 },
        type: 3
    },
    {
        maxdef: 74,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 22,
        slots: 0,
        name: "Queen Beetle Crura",
        skills: { "Marathon Runner": 1 },
        type: 3
    },
]