[
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 0,
        name: "King Beetle Head Alpha",
        skills: { "Evade Window": 2, Botanist: 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 0,
        name: "Butterfly Head Alpha",
        skills: { "Evade Window": 2, Botanist: 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 0,
        name: "King Beetle Chest Alpha",
        skills: { "Quick Sheath": 2, Botanist: 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 0,
        name: "Butterfly Chest Alpha",
        skills: { "Quick Sheath": 2, Botanist: 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 1,
        name: "King Beetle Arms Alpha",
        skills: { "Leap of Faith": 1, Botanist: 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 1,
        name: "Butterfly Arms Alpha",
        skills: { "Leap of Faith": 1, Botanist: 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 1,
        name: "King Beetle Waist Alpha",
        skills: { "Quick Sheath": 1, "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 1,
        name: "Butterfly Waist Alpha",
        skills: { "Quick Sheath": 1, "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 1,
        name: "King Beetle Legs Alpha",
        skills: { "Forager\u2019s Luck": 1, "Evade Window": 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 1,
        name: "Butterfly Legs Alpha",
        skills: { "Forager\u2019s Luck": 1, "Evade Window": 1 },
        type: 3
    },
]