[
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 1,
        name: "King Beetle Head Beta",
        skills: { "Evade Window": 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 1,
        name: "Butterfly Head Beta",
        skills: { "Evade Window": 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 1,
        name: "King Beetle Chest Beta",
        skills: { "Quick Sheath": 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 1,
        name: "Butterfly Chest Beta",
        skills: { "Quick Sheath": 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 1, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 2,
        name: "King Beetle Arms Beta",
        skills: { Botanist: 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 1, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 2,
        name: "Butterfly Arms Beta",
        skills: { Botanist: 2 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 1, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 2,
        name: "King Beetle Waist Beta",
        skills: { "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 1, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 2,
        name: "Butterfly Waist Beta",
        skills: { "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 1, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 2,
        name: "King Beetle Legs Beta",
        skills: { "Forager\u2019s Luck": 1 },
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 1, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 2,
        name: "Butterfly Legs Beta",
        skills: { "Forager\u2019s Luck": 1 },
        type: 3
    },
]