[
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Resistance Charm III",
        skills: { "Poison Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Attack Boost Charm III",
        skills: { "Attack Boost": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Defense Boost Charm III",
        skills: { "Defense Boost": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Resistance Charm III",
        skills: { "Paralysis Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Resistance Charm III",
        skills: { "Sleep Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stun Resistance Charm III",
        skills: { "Stun Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Windproof Charm III",
        skills: { Windproof: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Health Boost Charm III",
        skills: { "Health Boost": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Recovery Up Charm III",
        skills: { "Recovery Up": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fire Resistance Charm III",
        skills: { "Fire Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Water Resistance Charm III",
        skills: { "Water Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Thunder Resistance Charm III",
        skills: { "Thunder Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fire Attack Charm III",
        skills: { "Fire Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Water Attack Charm III",
        skills: { "Water Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Thunder Attack Charm III",
        skills: { "Thunder Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Attack Charm III",
        skills: { "Poison Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Attack Charm III",
        skills: { "Paralysis Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Attack Charm III",
        skills: { "Sleep Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Slugger Charm III",
        skills: { Slugger: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stamina Thief Charm III",
        skills: { "Stamina Thief": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Artillery Charm III",
        skills: { Artillery: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Hunger Resistance Charm III",
        skills: { "Hunger Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Guard Charm III",
        skills: { Guard: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Wide-Range Charm III",
        skills: { "Wide-Range": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Item Prolonger Charm III",
        skills: { "Item Prolonger": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Speed Eating Charm III",
        skills: { "Speed Eating": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Divine Blessing Charm III",
        skills: { "Divine Blessing": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Palico Rally Charm III",
        skills: { "Palico Rally": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Botanist Charm III",
        skills: { Botanist: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Geologist Charm III",
        skills: { Geologist: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Slinger Capacity Charm III",
        skills: { "Slinger Capacity": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stealth Charm III",
        skills: { Stealth: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Survival Expert Charm III",
        skills: { "Survival Expert": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Aquatic/Polar Mobility Charm III",
        skills: { "Aquatic/Polar Mobility": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Entomologist Charm III",
        skills: { Entomologist: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Intimidator Charm III",
        skills: { Intimidator: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Heavy Artillery Charm I",
        skills: { "Heavy Artillery": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Heavy Artillery Charm II",
        skills: { "Heavy Artillery": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Free Meal Charm",
        skills: { "Free Meal": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Scent Hound Charm",
        skills: { "Scent Hound": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fortify Charm",
        skills: { Fortify: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Horn Maestro Charm",
        skills: { "Horn Maestro": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Capacity Boost Charm",
        skills: { "Capacity Boost": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bleeding Resistance Charm III",
        skills: { "Bleeding Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Recovery Speed Charm III",
        skills: { "Recovery Speed": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Ice Resistance Charm III",
        skills: { "Ice Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blight Resistance Charm III",
        skills: { "Blight Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Ice Attack Charm III",
        skills: { "Ice Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Critical Eye Charm III",
        skills: { "Critical Eye": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Evade Window Charm III",
        skills: { "Evade Window": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Quick Sheath Charm III",
        skills: { "Quick Sheath": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Speed Sharpening Charm III",
        skills: { "Speed Sharpening": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Resistance Charm III",
        skills: { "Blast Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Dragon Resistance Charm III",
        skills: { "Dragon Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Dragon Attack Charm III",
        skills: { "Dragon Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Attack Charm III",
        skills: { "Blast Attack": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Critical Draw Charm II",
        skills: { "Critical Draw": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Special Ammo Boost Charm II",
        skills: { "Special Ammo Boost": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Marathon Runner Charm II",
        skills: { "Marathon Runner": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Constitution Charm III",
        skills: { Constitution: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Stamina Surge Charm II",
        skills: { "Stamina Surge": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Evade Extender Charm II",
        skills: { "Evade Extender": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bombardier Charm III",
        skills: { Bombardier: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Mushroomancer Charm II",
        skills: { Mushroomancer: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Free Elem/Ammo Up Charm II",
        skills: { "Free Elem/Ammo Up": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Handicraft Charm III",
        skills: { Handicraft: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Mud Puppy Charm",
        skills: { "Leap of Faith": 1, "Muck Resistance": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Trickshot Charm",
        skills: { Dungmaster: 1, Blindsider: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Hunter's Life Charm",
        skills: { "BBQ Master": 1, "Master Fisher": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Procurer's Charm",
        skills: { "Pro Transporter": 1, "Honey Hunter": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Gatherer's Charm",
        skills: { "Master Gatherer": 1, "Carving Pro": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Iron Skin Charm III",
        skills: { "Iron Skin": 0 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Earplugs Charm III",
        skills: { Earplugs: 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Tremor Resistance Charm II",
        skills: { "Tremor Resistance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Weakness Exploit Charm II",
        skills: { "Weakness Exploit": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Focus Charm II",
        skills: { Focus: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Partbreaker Charm II",
        skills: { Partbreaker: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Resentment Charm II",
        skills: { Resentment: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Heroics Charm II",
        skills: { Heroics: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Tool Specialist Charm III",
        skills: { "Tool Specialist": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Latent Power Charm II",
        skills: { "Latent Power": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Agitator Charm II",
        skills: { Agitator: 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Peak Performance Charm II",
        skills: { "Peak Performance": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Maximum Might Charm II",
        skills: { "Maximum Might": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Flinch Free Charm II",
        skills: { "Flinch Free": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Effluvia Resistance Charm III",
        skills: { "Effluvia Resistance": 3 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Normal Shots Charm",
        skills: { "Normal Shots": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Clearmind Charm",
        skills: { "Effluvia Expert": 1, "Heat Guard": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Rider's Charm",
        skills: { "Jump Master": 1, "Master Mounter": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Surveyor's Charm",
        skills: { "Scoutfly Range Up": 1, Scholar: 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Critical Boost Charm",
        skills: { "Critical Boost": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Power Prolonger Charm II",
        skills: { "Power Prolonger": 2 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Piercing Shots Charm",
        skills: { "Piercing Shots": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Spread/Power Shots Charm",
        skills: { "Spread/Power Shots": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Poison Functionality Charm",
        skills: { "Poison Functionality": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Paralysis Functionality Charm",
        skills: { "Paralysis Functionality": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Sleep Functionality Charm",
        skills: { "Sleep Functionality": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Blast Functionality Charm",
        skills: { "Blast Functionality": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Geomancy Charm",
        skills: { Detector: 1, "Forager\u2019s Luck": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Gale Charm",
        skills: { Airborne: 1, "Affinity Sliding": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Wyrmslayer Charm",
        skills: { "Elderseal Boost": 1, "Dragon Attack": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Bulwark Charm",
        skills: { Resuscitate: 1, "Guard Up": 1 },
        type: 3
    },
    {
        maxdef: 0,
        slotlevels: [0, 0, 0],
        sex: 3,
        resist: [0, 0, 0, 0, 0],
        part: 5,
        mindef: 0,
        slots: 0,
        name: "Fair Wind Charm",
        skills: { "Attack Boost": 1, "Divine Blessing": 1 },
        type: 3
    },
]