[
    {
        maxdef: 80,
        slotlevels: [2, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 1,
        name: "King Beetle Head Beta",
        skills: {"Stun Resistance": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [2, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Head Beta",
        skills: {"Stun Resistance": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 1,
        name: "King Beetle Chest Beta",
        skills: {"Health Boost": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Chest Beta",
        skills: {"Health Boost": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 1,
        name: "King Beetle Arms Beta",
        skills: {"Critical Eye": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Arms Beta",
        skills: {"Critical Eye": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [3, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 1,
        name: "King Beetle Waist Beta",
        skills: {"Defence Boost": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [3, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Waist Beta",
        skills: {"Defence Boost": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Legs Beta",
        skills: {"Marathon Runner": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 1,
        name: "King Beetle Legs Beta",
        skills: {"Marathon Runner": 2},
        type: 3
    },
]