[
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 1,
        name: "King Beetle Head Alpha",
        skills: {"Stun Resistance": 2, "Defense Boost": 1},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 0,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Head Alpha",
        skills: {"Stun Resistance": 2, "Defense Boost": 1},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 0,
        name: "King Beetle Chest Alpha",
        skills: {"Stun Resistance": 1, "Health Boost": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 1,
        mindef: 42,
        slots: 0,
        name: "Queen Beetle Chest Alpha",
        skills: {"Stun Resistance": 1, "Health Boost": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 0,
        name: "King Beetle Arms Alpha",
        skills: {"Critical Eye": 2, "Health Boost": 1},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 2,
        mindef: 42,
        slots: 0,
        name: "Queen Beetle Arms Alpha",
        skills: {"Critical Eye": 2, "Health Boost": 1},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 1,
        name: "King Beetle Waist Alpha",
        skills: {"Defense Boost": 2, "Marathon Runner": 1},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [1, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 3,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Waist Alpha",
        skills: {"Defense Boost": 2, "Marathon Runner": 1},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 2,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 1,
        name: "Queen Beetle Legs Alpha",
        skills: {"Critical Eye": 1, "Marathon Runner": 2},
        type: 3
    },
    {
        maxdef: 80,
        slotlevels: [0, 0, 0],
        sex: 1,
        resist: [-1, -1, 2, 0, 2],
        part: 4,
        mindef: 42,
        slots: 1,
        name: "King Beetle Legs Alpha",
        skills: {"Critical Eye": 1, "Marathon Runner": 2},
        type: 3
    },
]
